const router = {
    LOGIN: "/login",
    LOGINASWORKER: "/login-as-worker",
    FORGOTPASSWORDWORKER: "/forgot-password-worker",
    RESETPASSWORDWORKER: "/reset-password-worker",
    FORGOTPASSWORDCOMPANY: "/forgot-password-company",
    RESETPASSWORDCOMPANY: "/reset-password-company",
    LOGINASCOMPANY: "/login-as-company",
    REGISTER: "/register",
    REGISTERASWORKER: "/register-as-worker",
    REGISTERASCOMPANY: "/register-as-company",
    JOBS: "/jobs",
    MYAPPS: "/my-apps",
    MYCV: "/my-cv",
    EMPLOYERJOBSLIST: "/employer-jobs-list",
    EMPLOYERJOBSANNOUNCEMENT: "/employer-jobs-announcement",
    SEARCHCANDIDATES: "/search-candidates",
    EMPACCOUTDASHBORD: "/emp-account-dashbord",
    COMPANYPROFILE: "/company-profile",
    COMPANYEDITPROFILE: "/company-edit-profile",
    ORDERHISTORY: "/company-order-history",
    EMAILALERTSSETTINGS: "/company-email-alerts-settings",
};
export default router;